---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-portfolio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-portfolio
  template:
    metadata:
      labels:
        app: react-portfolio
    spec:
      containers:
        - name: react-portfolio-container
          image: snehaha/react-portfolio:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-portfolio-service
spec:
  selector:
    app: react-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
